[fix] Avoid malloc and free for message formatting
This also works around this build error on Windows:

    cl : Command line warning D9002 : ignoring unknown option '-std=c99'

    extension/_zipdecryptermodule.c(61): warning C4133: 'return': incompatible types - from 'PyObject *' to 'PyBytesObject *'
    extension/_zipdecryptermodule.c(68): warning C4133: 'return': incompatible types - from 'PyObject *' to 'PyBytesObject *'
    extension/_zipdecryptermodule.c(74): warning C4133: 'initializing': incompatible types - from 'PyObject *' to 'PyBytesObject *const '
    extension/_zipdecryptermodule.c(107): warning C4133: 'function': incompatible types - from 'const PyObject *' to 'const PyBytesObject *'
    extension/_zipdecryptermodule.c(107): warning C4133: 'return': incompatible types - from 'PyBytesObject *' to 'PyObject *'
    extension/_zipdecryptermodule.c(119): warning C4090: 'function': different 'const' qualifiers
    extension/_zipdecryptermodule.c(131): warning C4090: 'function': different 'const' qualifiers
    extension/_zipdecryptermodule.c(131): warning C4133: 'function': incompatible types - from 'PyObject *' to 'const PyBytesObject *'
    extension/_zipdecryptermodule.c(131): warning C4133: 'return': incompatible types - from 'PyBytesObject *' to 'PyObject *'
    extension/_zipdecryptermodule.c(134): error C2146: syntax error: missing ';' before identifier 'msg_len'
    extension/_zipdecryptermodule.c(134): error C2065: 'msg_len': undeclared identifier
    extension/_zipdecryptermodule.c(135): error C2065: 'msg_len': undeclared identifier
    extension/_zipdecryptermodule.c(136): error C2065: 'msg_len': undeclared identifier

It seems that the compiler does not recognize ssize_t, maybe because
-std=c99 is not valid for MSVC.